name: nordic_nrf_mesh_faradine
description: A Flutter plugin to enable mesh network management and communication using Nordic Semiconductor's SDKs.
version: 0.13.2
homepage: https://www.faradinesystems.com/
repository: https://github.com/JosephFaradine/nrf_mesh_plugin

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # BLE handling
  flutter_reactive_ble: ^5.0.2
  rxdart: ^0.27.5
  retry: ^3.1.0
  # Models
  json_annotation: ^4.7.0
  freezed_annotation: ^2.1.0
  # static analysis
  meta: ^1.8.0
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  json_serializable: ^6.5.1
  freezed: ^2.1.1
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.faradine.nordic_nrf_mesh_faradine
        pluginClass: NordicNrfMeshPlugin
      ios:
        pluginClass: NordicNrfMeshPlugin
